export const IMAGE_USAGE_RETENTION_DAYS = 7;
export const DEFAULT_IMAGE_MAX_CACHE_COUNT = 100;
export const DEFAULT_IMAGE_CLEANUP_INTERVAL_HOURS = 24;
export const DEFAULT_IMAGE_RATE_LIMIT_SECONDS = 0;
export const DEFAULT_IMAGE_DAILY_LIMIT_COUNT = 10;
export const DEFAULT_IMAGE_MAX_SIZE_MB = 10;
